---
name: Release-Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          default-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-types: |
            [
              {"type":"feat","section":"Nouveautés","hidden":false},
              {"type":"improve","section":"Améliorations","hidden":false},
              {"type":"fix","section":"Corrections (bugs, typos...)","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"refactor","section":"Technique","hidden":false},
              {"type":"revert","section":"Technique","hidden":false},
              {"type":"style","section":"Technique","hidden":false},
              {"type":"test","section":"Technique","hidden":false},
              {"type":"chore","section":"Technique","hidden":false},
              {"type":"perf","section":"Technique","hidden":false},
              {"type":"build","section":"Technique","hidden":false},
              {"type":"ci","section":"Technique","hidden":false}
            ]
